### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by stephenmathieson** [then/then-levelup#4]
```
> var db = require('then-levelup')(require('levelup')('./mydb'));
TypeError: Cannot read property 'bind' of undefined
    at then (/somewhere/node_modules/then-levelup/index.js:32:44)
    at repl:1:33
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
> 
```

**Comment by stuartpb** [comment]
This is a side-effect of #2, and would be fixed if and when @ForbesLindesay pushes the latest tag (v1.0.2) to npm (#3).
